### PR TITLE
added Readme file

### PR DESCRIPTION
**Pull request by champ3oy**
I added a readme file to help people who don't know how to run python projects get started. It is very basic, please feel free to add more stuff that I missed

### CODE REVIEW

**Comment by ayushmokal** [comment]
Yes If you can add a readme with good Description and info about the project will be great actually

**Comment by advaitpaliwal** [comment]
thanks! will spend some time this weekend cleaning up the repo and adding docs.

**Comment by champ3oy** [comment]
> thanks! will spend some time this weekend cleaning up the repo and adding docs.

sure

**Comment by advaitpaliwal** [comment]
merged your pr, thanks!

**Comment by Just-Moh-it** [comment]
W @champ3oy!

**Pull request merged**
